version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        title: "chore(deps): Update npm dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:07"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
        title: "chore(actions): Update GitHub actions"
